export enum ECustomEvents {
  AddToCart = 'add_to_cart',
  InitiatedCheckout = 'begin_checkout',
  PaymentInitiated = 'payment_initiated',
  PickStore = 'pick_store',
  RemoveFromCart = 'remove_from_cart',
  SearchStore = 'search_store',
  ViewProduct = 'view_item',
  ViewProductList = 'view_item_list',
  UpdateProfile = 'update_profile',
}

// Firebase Analytics
export enum EAppEvents {
  AddPaymentInfo = 'add_payment_info',
  AddToCart = 'add_to_cart',
  AddVoucher = 'add_voucher',
  AdjustPinMap = 'adjust_pin_map',
  BulkOrderContactUs = 'bulkorder_contact_us',
  CheckoutDeliveryTabClick = 'checkout_delivery_tab_click',
  CheckoutOrderTypeTab = 'checkout_tab_click',
  CheckoutPickupTabClick = 'checkout_pickup_tab_click',
  CloseFullScreenSignUpPopup = 'close_fullscreen_sign_up_popup',
  CloseHalfScreenSignUpPopup = 'close_halfscreen_sign_up_popup',
  DeleteSavedAddress = 'delete_saved_address',
  DeleteSavedAddressSuccess = 'delete_saved_address_succesfull',
  DeliveryAddNewPayment = 'delivery_add_new_payment',
  DeliveryApplyVoucher = 'delivery_apply_voucher',
  DeliveryChangePayment = 'delivery_change_payment',
  DeliveryCheckoutChangeAddress = 'delivery_checkout_change_address',
  DeliveryCheckoutChangeStore = 'delivery_checkout_change_store',
  DeliveryCheckoutContinue = 'delivery_checkout_continue',
  DeliveryConfirmPaymentMethod = 'delivery_confirm_payment_method',
  DeliveryOrderCheckout = 'delivery_order_checkout',
  DeliveryPayNow = 'delivery_checkout_pay_now',
  DeliveryViewCart = 'delivery_view_cart',
  EditSavedAddress = 'edit_saved_address_menu',
  EditSavedAddressSuccess = 'edit_saved_address_menu_success',
  ErrorOccurs = 'error_occurs',
  HomeOrderTypeTab = 'homescreen_tab_click',
  NextFullScreenSignUpPopup = 'next_fullscreen_sign_up_popup',
  NextHalfScreenSignUpPopup = 'next_halfscreen_sign_up_popup',
  NotShownSignUpPopup = 'not_shown_sign_up_popup',
  OrderDetailTrack = 'order_detail_track',
  PickupApplyVoucher = 'pickup_apply_voucher',
  PickupAddNewPayment = 'pickup_add_new_payment',
  PickupChangePayment = 'pickup_change_payment',
  PickupCheckoutChangeStore = 'pickup_checkout_change_store',
  PickupCheckoutContinue = 'pickup_checkout_continue',
  PickupConfirmPaymentMethod = 'pikcup_confirm_payment_method',
  PickupOrderCheckout = 'pickup_order_checkout',
  PickupPayNow = 'pickup_checkout_pay_now',
  PickupSelectPickupTime = 'pickup_select_pickup_time',
  PickupViewCart = 'pickup_view_cart',
  Purchase = 'purchase',
  SaveAddress = 'save_address',
  ShowFullScreenSignUpPopup = 'show_fullscreen_sign_up_popup',
  ShowHalfScreenSignUpPopup = 'show_halfscreen_sign_up_popup',
  SignUpCompleted = 'sign_up_completed',
  StoreListOrderTypeTab = 'storelist_tab_click',
  StoreSearch = 'storelist_seach_click',
  TapAddMoreLocation = 'add_more_location',
  TapEditFavoriteLocation = 'edit_favorite_location',
  UseVoucher = 'use_voucher',
  ViewCart = 'view_cart',
  ViewProduct = 'view_item',
  ViewProductList = 'view_item_list',
  PickupAddToCart = 'pickup_add_to_cart',
  DeliveryAddToCart = 'delivery_add_to_cart',
  HomeDeliveryTabClick = 'home_delivery_tab_click',
  HomePickupTabClick = 'home_pickup_tab_click',
  StoreListDeliveryTabClick = 'storelist_delivery_tab_click',
  StoreListPickupTabClick = 'storelist_pickup_tab_click',
}

// Facebook Events
export enum EFBEvents {
  ViewProduct = 'fb_mobile_content_view',
  AddToCart = 'fb_mobile_add_to_cart',
  AddPaymentInfo = 'fb_mobile_add_payment_info',
  Purchase = 'fb_mobile_purchase',
  InitiatedCheckout = 'fb_mobile_initiated_checkout',
}

// AppFlyers
export enum EAppFlyersEvents {
  ViewProduct = 'af_content_view',
  AddToCart = 'af_add_to_cart',
  AddPaymentInfo = 'af_add_payment_info',
  Purchase = 'af_purchase',
  InitiatedCheckout = 'af_initiated_checkout',
}
