// [PAYMENT_PROVIDER]_[PAYMENT_METHOD]_[ERROR_REASON]
export enum EPaymentExceptionCode {
  ADYEN_CREATE_PAYMENT = 'PAY0001',
  ADYEN_APPLEPAY_SHOW_APPLEPAY_MODALS = 'PAY0002',
  TAPPAY_APPLEPAY_SHOW_APPLEPAY_MODALS = 'PAY0003',
}
