import 'react-native';
import {IPromotion} from '@appTypes/promotion.type';
import {getCampaignDisplayName} from '.';

it('getCampaignDisplayName works well', () => {
  const sampleCampaign: IPromotion = {
    id: 990,
    created: '2021-07-08T03:41:14.493084Z',
    applicationId: 36,
    userId: 103,
    name: 'Copy of ID DEV - #SemangatDiRumah Gratis Cemilan Khusus Yosef',
    description: 'description',
    attributes: {
      campaignType: 'promotion',
      descLocale: 'description',
      displayName: '#SemangatDiRumahXYZ',
      headline: '#SemangatDiRumah Gratis Cemilan',
      headlineLocale: '#SemangatDiRumah Gratis Cemilan',
      headlineSmall: '#SemangatDiRumah Gratis Cemilan',
      headlineSmallLocale: '#SemangatDiRumah Gratis Cemilan',
      image:
        'https://s3.ap-southeast-1.amazonaws.com/talonone-assets.flash-coffee.com/Gratis+Snack.png',
      imageLocale: '#SemangatDiRumah Gratis Cemilan',
      isFeatured: false,
      isForceApplied: false,
      nameLocale: '#SemangatDiRumah Gratis Cemilan',
      promotionCategory: 'Reward',
      promotionCost: 0,
      promotionMaxUsage: 5,
    },
    state: 'enabled',
    activeRulesetId: 4346,
    tags: ['Promotion'],
    features: ['coupons', 'referrals', 'loyalty'],
    couponSettings: {
      validCharacters: [
        '3',
        '4',
        '5',
        '7',
        '8',
        '9',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'H',
        'J',
        'K',
        'L',
        'M',
        'N',
        'P',
        'Q',
        'R',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
      ],
      couponPattern: '####-####',
    },
    referralSettings: {
      validCharacters: [
        '3',
        '4',
        '5',
        '7',
        '8',
        '9',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'H',
        'J',
        'K',
        'L',
        'M',
        'N',
        'P',
        'Q',
        'R',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
      ],
      couponPattern: '####-####',
    },
    limits: [],
    campaignGroups: [],
    couponRedemptionCount: 0,
    referralRedemptionCount: 0,
    discountCount: 0,
    discountEffectCount: 0,
    couponCreationCount: 0,
    referralCreationCount: 0,
    createdLoyaltyPointsCount: 0,
    createdLoyaltyPointsEffectCount: 0,
    redeemedLoyaltyPointsCount: 0,
    redeemedLoyaltyPointsEffectCount: 0,
    lastActivity: '2021-07-08T05:16:11.039907Z',
    updated: '2021-07-08T12:05:30.088507Z',
    updatedBy: 'Ali Irawan',
  };

  const sampleWithoutDisplayNameCampaign: IPromotion = {
    id: 990,
    created: '2021-07-08T03:41:14.493084Z',
    applicationId: 36,
    userId: 103,
    name: 'Copy of ID DEV - #SemangatDiRumah Gratis Cemilan Khusus Yosef',
    description: 'description',
    attributes: {
      campaignType: 'promotion',
      descLocale: 'description',
      headline: '#SemangatDiRumah Gratis Cemilan',
      headlineLocale: '#SemangatDiRumah Gratis Cemilan',
      headlineSmall: '#SemangatDiRumah Gratis Cemilan',
      headlineSmallLocale: '#SemangatDiRumah Gratis Cemilan',
      image:
        'https://s3.ap-southeast-1.amazonaws.com/talonone-assets.flash-coffee.com/Gratis+Snack.png',
      imageLocale: '#SemangatDiRumah Gratis Cemilan',
      isFeatured: false,
      isForceApplied: false,
      nameLocale: '#SemangatDiRumah Gratis Cemilan',
      promotionCategory: 'Reward',
      promotionCost: 0,
      promotionMaxUsage: 5,
    },
    state: 'enabled',
    activeRulesetId: 4346,
    tags: ['Promotion'],
    features: ['coupons', 'referrals', 'loyalty'],
    couponSettings: {
      validCharacters: [
        '3',
        '4',
        '5',
        '7',
        '8',
        '9',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'H',
        'J',
        'K',
        'L',
        'M',
        'N',
        'P',
        'Q',
        'R',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
      ],
      couponPattern: '####-####',
    },
    referralSettings: {
      validCharacters: [
        '3',
        '4',
        '5',
        '7',
        '8',
        '9',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'H',
        'J',
        'K',
        'L',
        'M',
        'N',
        'P',
        'Q',
        'R',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
      ],
      couponPattern: '####-####',
    },
    limits: [],
    campaignGroups: [],
    couponRedemptionCount: 0,
    referralRedemptionCount: 0,
    discountCount: 0,
    discountEffectCount: 0,
    couponCreationCount: 0,
    referralCreationCount: 0,
    createdLoyaltyPointsCount: 0,
    createdLoyaltyPointsEffectCount: 0,
    redeemedLoyaltyPointsCount: 0,
    redeemedLoyaltyPointsEffectCount: 0,
    lastActivity: '2021-07-08T05:16:11.039907Z',
    updated: '2021-07-08T12:05:30.088507Z',
    updatedBy: 'Ali Irawan',
  };

  expect(getCampaignDisplayName(sampleCampaign)).toBe('#SemangatDiRumahXYZ');
  expect(getCampaignDisplayName(sampleWithoutDisplayNameCampaign)).toBe(
    'Copy of ID DEV - #SemangatDiRumah Gratis Cemilan Khusus Yosef',
  );
  expect(getCampaignDisplayName(null)).toBe('');
  expect(getCampaignDisplayName(undefined)).toBe('');
});
